[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=86400"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' www.google-analytics.com;"